global:
  scrape_interval: 15s
  scrape_timeout: 12s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - thesis-backend_alertmanager:9093
rule_files:
  - ./rules/*.yml

scrape_configs:
  - job_name: "prometheus"
    static_configs:
    - targets: ["thesis-backend_prometheus:9090"]
  - job_name: "alertmanager"
    static_configs:
    - targets: ["thesis-backend_alertmanager:9093"]
  - job_name: "grafana"
    static_configs:
    - targets: ["thesis-backend_grafana:3000"]
  - job_name: "thesis-backend-mqtt-exporter"
    static_configs:
    - targets: ["thesis-backend_thesis-backend-mqtt-exporter:9000"]